#!/usr/bin/env python3
"""Regenerate consumer fallback snapshots from evan-public-data.

Reads structural reference.json + reference.EN.json and writes:
  ../evan-backend/supabase/functions/_shared/public_activity_data.ts
  ../evan_frontend_mobile/lib/data/public_activity_data.dart

These are fallback caches only; runtime consumers fetch reference.json and the
locale file directly per ADR-0055 Option C.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
BACKEND_OUT = ROOT.parent / "evan-backend/supabase/functions/_shared/public_activity_data.ts"
FRONTEND_OUT = ROOT.parent / "evan_frontend_mobile/lib/data/public_activity_data.dart"

ref = json.loads((DATA / "reference.json").read_text())
lang = json.loads((DATA / "reference.EN.json").read_text())
contexts = ref["contexts"]
activities = sorted({a for ids in contexts.values() for a in ids})
categories = ref["locationCategories"]
grants = ref["amenityActivityGrants"]


def q(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


header = """// Generated by evan-public-data/scripts/generate_snapshots.py (ADR-0055).
// Fallback snapshot for resilience. Runtime source of truth:
// ../evan-public-data/data/reference.json + reference.{LOCALE}.json.
// Do not edit by hand; re-run the generator after changing public data.

"""

ts_context_entries = "\n".join(
    "  %s: %s," % (q(ctx), q(ids))
    for ctx, ids in contexts.items()
)
ts_category_entries = "\n".join(
    "  { id: %s, isPublicVenue: %s, sourceTags: %s, activityIds: %s },"
    % (q(c["id"]), q(c["isPublicVenue"]), q(c.get("sourceTags", [])), q(c["activityIds"]))
    for c in categories
)
ts_grant_entries = "\n".join(
    "  %s: %s," % (q(grant_id), q(activity_ids))
    for grant_id, activity_ids in grants.items()
)

ts_body = f"""{header}
export const CONTEXTS: Readonly<Record<string, readonly string[]>> = {{
{ts_context_entries}
}};

export interface VenueCategory {{
  id: string;
  isPublicVenue: boolean;
  sourceTags: readonly string[];
  activityIds: readonly string[];
}}

export const VENUE_CATEGORIES: readonly VenueCategory[] = [
{ts_category_entries}
] as const;

export const AMENITY_ACTIVITY_GRANTS: Readonly<Record<string, readonly string[]>> = {{
{ts_grant_entries}
}};

const SOURCE_TO_CATEGORY = new Map<string, string>(
  VENUE_CATEGORIES.flatMap((category) =>
    category.sourceTags.map((tag) => [tag, category.id] as const)
  ),
);

export function canonicalVenueCategoryForSourceTag(sourceTag: string): string | null {{
  return SOURCE_TO_CATEGORY.get(sourceTag) ?? null;
}}

export function activityTagsForVenueCategory(category: string): string[] {{
  return VENUE_CATEGORIES.find((c) => c.id === category)?.activityIds.slice() ?? [];
}}

export function activityTagsForVenueCategoryAndAmenities(
  category: string,
  amenities: string[],
): string[] {{
  const base = activityTagsForVenueCategory(category);
  const extra = amenities.flatMap((amenity) => AMENITY_ACTIVITY_GRANTS[amenity] ?? []);
  return [...new Set([...base, ...extra])];
}}

export function isPublicVenueCategory(category: string): boolean {{
  return VENUE_CATEGORIES.find((c) => c.id === category)?.isPublicVenue ?? false;
}}

export function activityTagsForSourceTag(sourceTag: string): string[] {{
  const category = canonicalVenueCategoryForSourceTag(sourceTag);
  return category ? activityTagsForVenueCategory(category) : [];
}}

export function activitiesForLocationCategoryAndContext(
  categoryId: string,
  context: string,
): string[] {{
  const allowed = activityTagsForVenueCategory(categoryId);
  return (CONTEXTS[context] ?? []).filter((id) => allowed.includes(id));
}}
"""

dart_context_entries = "\n".join(
    "  %s: %s," % (q(ctx), q(ids))
    for ctx, ids in contexts.items()
)
dart_context_name_entries = "\n".join(
    "  %s: %s," % (q(ctx), q(lang["contexts"].get(ctx, ctx)))
    for ctx in contexts
)
dart_activity_name_entries = "\n".join(
    "  %s: %s," % (q(a), q(lang["activities"].get(a, a)))
    for a in activities
)
dart_category_entries = "\n".join(
    "  VenueCategory(\n"
    "    id: %s,\n"
    "    names: %s,\n"
    "    isPublicVenue: %s,\n"
    "    sourceTags: %s,\n"
    "    activityIds: %s,\n"
    "  )," % (q(c["id"]), q({"en": lang["locationCategories"].get(c["id"], c["id"])}), q(c["isPublicVenue"]), q(c.get("sourceTags", [])), q(c["activityIds"]))
    for c in categories
)
dart_grant_entries = "\n".join(
    "  %s: %s," % (q(grant_id), q(activity_ids))
    for grant_id, activity_ids in grants.items()
)

dart_body = f"""{header}
class VenueCategory {{
  final String id;
  final Map<String, String> names;
  final bool isPublicVenue;
  final List<String> sourceTags;
  final List<String> activityIds;

  const VenueCategory({{
    required this.id,
    required this.names,
    required this.isPublicVenue,
    required this.sourceTags,
    required this.activityIds,
  }});

  factory VenueCategory.fromJson(Map<String, dynamic> json) {{
    return VenueCategory(
      id: json['id'] as String? ?? '',
      names: (json['names'] as Map<String, dynamic>? ?? const {{}})
          .map((key, value) => MapEntry(key, value.toString())),
      isPublicVenue: json['isPublicVenue'] as bool? ?? false,
      sourceTags: (json['sourceTags'] as List<dynamic>? ?? const [])
          .map((e) => e.toString())
          .toList(),
      activityIds: (json['activityIds'] as List<dynamic>? ?? const [])
          .map((e) => e.toString())
          .toList(),
    );
  }}
}}

const kContexts = <String, List<String>>{{
{dart_context_entries}
}};

const kContextNames = <String, String>{{
{dart_context_name_entries}
}};

const kActivityNames = <String, String>{{
{dart_activity_name_entries}
}};

const kVenueCategories = <VenueCategory>[
{dart_category_entries}
];

const kAmenityActivityGrants = <String, List<String>>{{
{dart_grant_entries}
}};

String? activityDisplayName(String activityId, {{String language = 'en'}}) {{
  return language == 'en' ? kActivityNames[activityId] : kActivityNames[activityId];
}}

String? contextDisplayName(String contextId, {{String language = 'en'}}) {{
  return kContextNames[contextId];
}}

List<String> activityTagsForVenueCategory(String categoryId) {{
  for (final category in kVenueCategories) {{
    if (category.id == categoryId) {{
      return List.unmodifiable(category.activityIds);
    }}
  }}
  return const <String>[];
}}

List<String> activityTagsForVenueCategoryAndAmenities(
  String categoryId,
  List<String> amenities,
) {{
  final base = activityTagsForVenueCategory(categoryId);
  final extra = <String>[];
  for (final amenity in amenities) {{
    extra.addAll(kAmenityActivityGrants[amenity] ?? const <String>[]);
  }}
  return <String>{{...base, ...extra}}.toList();
}}

List<String> activityTagsForSourceTag(String sourceTag) {{
  for (final category in kVenueCategories) {{
    if (category.sourceTags.contains(sourceTag)) {{
      return List.unmodifiable(category.activityIds);
    }}
  }}
  return const <String>[];
}}

List<String> activitiesForLocationCategoryAndContext(String categoryId, String context) {{
  final allowed = activityTagsForVenueCategory(categoryId).toSet();
  return (kContexts[context] ?? const <String>[])
      .where((id) => allowed.contains(id))
      .toList();
}}
"""

BACKEND_OUT.write_text(ts_body)
FRONTEND_OUT.write_text(dart_body)
print(f"Wrote {BACKEND_OUT}")
print(f"Wrote {FRONTEND_OUT}")
